version: '3.9'
services:
  haproxy:
    restart: on-failure
    container_name: haproxy
    extra_hosts:
      - "svc01.example.test:127.0.0.1"
      - "svc02.example.test:127.0.0.1"
    volumes:
      - "./config:/usr/local/etc/haproxy:ro"
    ports:
      - "8900:8900"
      - "8901:8901"
    environment:
      - VV_HAPROXY_DEBUG=${VV_HAPROXY_DEBUG:-true}
      - VV_HAPROXY_FE_HTTP_LISTEN_ADDR=${VV_HAPROXY_FE_HTTP_LISTEN_ADDR:-:8900}
      - VV_HAPROXY_FE_METRICS_LISTEN_ADDR=${VV_HAPROXY_FE_METRICS_LISTEN_ADDR:-:8901}
    build:
      context: .

